### ISSUE TITLE
[Bug]: Build workflow does not load GHTOKENWORKFLOW secret

### ISSUE THREAD

**Issue by cegekaJG** [microsoft/AL-Go#1267]
### AL-Go version

5bb4f65ffe64f5328a70a288d04640786aa467ec (modified)

### Describe the issue

After updating the AL Go system files with the latest commits from the main branch, my repos get the following error during the Build pipeline:

```
Error: Unexpected error when running action. Error Message: The property 'GHTOKENWORKFLOW' cannot be found on this object. Verify that the property exists., StackTrace:
at CheckAppDependencyProbingPaths, /home/runner/work/_actions/cegekaJG/AL-Go-Actions/cegeka/AL-Go-Helper.ps1: line 1167 <-
at DownloadDependenciesFromProbingPaths, /home/runner/work/_actions/cegekaJG/AL-Go-Actions/cegeka/DownloadProjectDependencies/DownloadProjectDependencies.Action.ps1: line 22 <-
at <ScriptBlock>, /home/runner/work/_actions/cegekaJG/AL-Go-Actions/cegeka/DownloadProjectDependencies/DownloadProjectDependencies.Action.ps1: line 116 <-
at <ScriptBlock>, /home/runner/work/_temp/8c9f3879-7551-485f-bf66-cff159fd047f.ps1: line 3 <-
at <ScriptBlock>, /home/runner/work/_actions/cegekaJG/AL-Go-Actions/cegeka/Invoke-AlGoAction.ps1: line 17 <-
at <ScriptBlock>, /home/runner/work/_temp/8c9f3879-7551-485f-bf66-cff159fd047f.ps1: line 2 <-
at <ScriptBlock>, <No file>: line 1
Error: Process completed with exit code 1.
```

I noticed that the workflow seems to fail because the step "Read Secrets" no longer loads the secret `GHTOKENWORKFLOW`. Comparing commits shows that there has been a major rework of the `Actions/ReadSecrets/ReadSecrets.ps1` file. See at the end for more info.

### Expected behavior

This is the log of the last successful build, performed before the update:

```
Run cegekaJG/AL-Go-Actions/ReadSecrets@cegeka
  with:
    shell: pwsh
    gitHubSecrets: {
    "GHTOKENWORKFLOW": "***",
    "LICENSEFILEURL": "***",
    "FLFLICENSEFILEURL": "***",
    "github_token": "***"
  }
    getSecrets: licenseFileUrl,codeSignCertificateUrl,*codeSignCertificatePassword,keyVaultCertificateUrl,*keyVaultCertificatePassword,keyVaultClientId,gitHubPackagesContext,applicationInsightsConnectionString,appDependencyProbingPathsSecrets,AZURE_CREDENTIALS
    useGhTokenWorkflowForPush: false
  env:
    ALGoOrgSettings: 
    ALGoRepoSettings: 
    artifact: https://bcartifacts-exdbf9fwegejdqak.b0[2](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/10596074488/job/29363248655#step:4:2).azurefd.net/sandbox/24.[3](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/10596074488/job/29363248655#step:4:3).21374.21570/at
    keyVaultCodesignCertificateName: 
    generateDependencyArtifact: True
    doNotRunTests: False
    doNotSignApps: False
    useCompilerFolder: True
    Settings: {"repoName":"GAR.EDI","githubRunnerShell":"pwsh","licenseFileUrlSecretName":"licenseFileUrl","runNumberOffset":0,"installTestRunner":false,"testFolders":[],"versioningStrategy":0,"unusedALGoSystemFiles":[],"excludeEnvironments":[],"enableUICop":true,"$schema":"https://raw.githubusercontent.com/microsoft/AL-Go/v5.1/Schema/algosettingssyntax.json","doNotBuildTests":false,"bcptTestFolders":[],"artifact":"https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/2[4](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/10596074488/job/29363248655#step:4:4).3.21374.21570/at","repoVersion":"1.0","templateFiles":[".github/DeployTo*.ps1",".schemas/*"],"keyVaultName":"","configPackages":[],"buildModes":["Default"],"alwaysBuildAllProjects":false,"cacheImageName":"my","ghTokenWorkflowSecretName":"ghTokenWorkflow","enableExternalRulesets":false,"testDependencies":[],"alDoc":{"continuousDeployment":false,"deployToGitHubPages":true,"maxReleases":3,"groupByProject":true,"includeProjects":[],"excludeProjects":[],"header":"Documentation for {REPOSITORY} {VERSION}","footer":"Documentation for <a href=\"https://github.com/{REPOSITORY}\">{REPOSITORY}</a> made with <a href=\"https://aka.ms/AL-Go\">AL-Go for GitHub</a>, <a href=\"https://go.microsoft.com/fwlink/?linkid=2247728\">ALDoc</a> and <a href=\"https://dotnet.github.io/docfx\">DocFx</a>","defaultIndexMD":"## Reference documentation\\n\\nThis is the generated reference documentation for [{REPOSITORY}](https://github.com/{REPOSITORY}).\\n\\nYou can use the navigation bar at the top and the table of contents to the left to navigate your documentation.\\n\\nYou can change this content by creating/editing the **{INDEXTEMPLATERELATIVEPATH}** file in your repository or use the alDoc:defaultIndexMD setting in your repository settings file (.github/AL-Go-Settings.json)\\n\\n{RELEASENOTES}","defaultReleaseMD":"## Release reference documentation\\n\\nThis is the generated reference documentation for [{REPOSITORY}](https://github.com/{REPOSITORY}).\\n\\nYou can use the navigation bar at the top and the table of contents to the left to navigate your documentation.\\n\\nYou can change this content by creating/editing the **{INDEXTEMPLATERELATIVEPATH}** file in your repository or use the alDoc:defaultReleaseMD setting in your repository settings file (.github/AL-Go-Settings.json)\\n\\n{RELEASENOTES}"},"installTestLibraries":false,"appFolders":[],"bcptThresholds":{"DurationWarning":10,"DurationError":2[5](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/10596074488/job/29363248655#step:4:5),"NumberOfSqlStmtsWarning":5,"NumberOfSqlStmtsError":10},"shell":"pwsh","useCompilerFolder":true,"powerPlatformSolutionFolder":"","skipUpgrade":true,"projects":[],"projectName":"Garant EDI","installTestFramework":false,"appDependencies":[],"installTestApps":[],"appSourceCopMandatoryAffixes":[],"generateDependencyArtifact":true,"codeSignCertificateUrlSecretName":"codeSignCertificateUrl","githubRunner":"ubuntu-latest","country":"at","runs-on":"ubuntu-latest","additionalCountries":[],"cacheKeepDays":3,"enablePerTenantExtensionCop":false,"customCodeCops":["https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/latest/download/BusinessCentral.LinterCop.current.dll"],"keyVaultCertificateUrlSecretName":"","doNotPublishApps":true,"sendExtendedTelemetryToMicrosoft":false,"adminCenterApiCredentialsSecretName":"adminCenterApiCredentials","type":"PTE","environments":[],"rulesetFile":"CegekaAT.ruleset.json","enableCodeAnalyzersOnTestApps":false,"codeSignCertificatePasswordSecretName":"codeSignCertificatePassword","microsoftTelemetryConnectionString":"InstrumentationKey=cd2cc[6](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/10596074488/job/29363248655#step:4:6)3e-0f37-4968-b99a-532411a314b8;IngestionEndpoint=https://northeurope-2.in.applicationinsights.azure.com/","enableTaskScheduler":false,"doNotRunBcptTests":false,"appDependencyProbingPaths":[{"authTokenSecret":"GHTOKENWORKFLOW","projects":"*","release_status":"release","repo":"https://github.com/CBS-BC-AT/GAR.Base","version":"24.8.0"}],"memoryLimit":"","failOn":"error","deliverToAppSource":{"mainAppFolder":"","productId":"","includeDependencies":[],"continuousDelivery":false},"assignPremiumPlan":false,"templateSha":"5[7](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/10596074488/job/29363248655#step:4:7)8f30d0065aa17fd6bb8513c7eef725e5474c0[8](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/10596074488/job/29363248655#step:4:8)","appRevision":0,"partnerTelemetryConnectionString":"","templateBranch":"","obsoleteTagMinAllowedMajorMinor":"","useProjectDependencies":false,"installApps":[],"updateDependencies":false,"installOnlyReferencedApps":true,"installPerformanceToolkit":false,"fullBuildPatterns":[],"treatTestFailuresAsWarnings":false,"applicationDependency":"18.0.0.0","doNotRunTests":false,"applicationInsightsConnectionStringSecretName":"applicationInsightsConnectionString","companyName":"","appBuild":6,"keyVaultCodesignCertificateName":"","templateUrl":"https://github.com/cegekaJG/AL-Go-PTE@cegeka","pullRequestTrigger":"pull_request_target","enableCodeCop":true,"keyVaultCertificatePasswordSecretName":"","keyVaultClientIdSecretName":"","doNotSignApps":false,"UpdateGitHubGoSystemFilesSchedule":"0 2 * * 1,3,5","vsixFile":"latest"}
Run /home/runner/work/_actions/cegekaJG/AL-Go-Actions/cegeka/ReadSecrets/../Invoke-AlGoAction.ps1 -ActionName "ReadSecrets" -Action {
  /home/runner/work/_actions/cegekaJG/AL-Go-Actions/cegeka/ReadSecrets/../Invoke-AlGoAction.ps1 -ActionName "ReadSecrets" -Action {
    /home/runner/work/_actions/cegekaJG/AL-Go-Actions/cegeka/ReadSecrets/ReadSecrets.ps1 -gitHubSecrets '{
    "GHTOKENWORKFLOW": "***",
    "LICENSEFILEURL": "***",
    "FLFLICENSEFILEURL": "***",
    "github_token": "***"
  }' -getSecrets $ENV:_getSecrets -useGhTokenWorkflowForPush $ENV:_useGhTokenWorkflowForPush
  }
  shell: /usr/bin/pwsh -command ". '{0}'"
  env:
    ALGoOrgSettings: 
    ALGoRepoSettings: 
    artifact: https://bcartifacts-exdbf[9](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/10596074488/job/29363248655#step:4:9)fwegejdqak.b02.azurefd.net/sandbox/24.3.21374.21570/at
    keyVaultCodesignCertificateName: 
    generateDependencyArtifact: True
    doNotRunTests: False
    doNotSignApps: False
    useCompilerFolder: True
    Settings: {"repoName":"GAR.EDI","githubRunnerShell":"pwsh","licenseFileUrlSecretName":"licenseFileUrl","runNumberOffset":0,"installTestRunner":false,"testFolders":[],"versioningStrategy":0,"unusedALGoSystemFiles":[],"excludeEnvironments":[],"enableUICop":true,"$schema":"https://raw.githubusercontent.com/microsoft/AL-Go/v5.1/Schema/algosettingssyntax.json","doNotBuildTests":false,"bcptTestFolders":[],"artifact":"https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/24.3.21374.21570/at","repoVersion":"1.0","templateFiles":[".github/DeployTo*.ps1",".schemas/*"],"keyVaultName":"","configPackages":[],"buildModes":["Default"],"alwaysBuildAllProjects":false,"cacheImageName":"my","ghTokenWorkflowSecretName":"ghTokenWorkflow","enableExternalRulesets":false,"testDependencies":[],"alDoc":{"continuousDeployment":false,"deployToGitHubPages":true,"maxReleases":3,"groupByProject":true,"includeProjects":[],"excludeProjects":[],"header":"Documentation for {REPOSITORY} {VERSION}","footer":"Documentation for <a href=\"https://github.com/{REPOSITORY}\">{REPOSITORY}</a> made with <a href=\"https://aka.ms/AL-Go\">AL-Go for GitHub</a>, <a href=\"https://go.microsoft.com/fwlink/?linkid=2247728\">ALDoc</a> and <a href=\"https://dotnet.github.io/docfx\">DocFx</a>","defaultIndexMD":"## Reference documentation\\n\\nThis is the generated reference documentation for [{REPOSITORY}](https://github.com/{REPOSITORY}).\\n\\nYou can use the navigation bar at the top and the table of contents to the left to navigate your documentation.\\n\\nYou can change this content by creating/editing the **{INDEXTEMPLATERELATIVEPATH}** file in your repository or use the alDoc:defaultIndexMD setting in your repository settings file (.github/AL-Go-Settings.json)\\n\\n{RELEASENOTES}","defaultReleaseMD":"## Release reference documentation\\n\\nThis is the generated reference documentation for [{REPOSITORY}](https://github.com/{REPOSITORY}).\\n\\nYou can use the navigation bar at the top and the table of contents to the left to navigate your documentation.\\n\\nYou can change this content by creating/editing the **{INDEXTEMPLATERELATIVEPATH}** file in your repository or use the alDoc:defaultReleaseMD setting in your repository settings file (.github/AL-Go-Settings.json)\\n\\n{RELEASENOTES}"},"installTestLibraries":false,"appFolders":[],"bcptThresholds":{"DurationWarning":[10](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/10596074488/job/29363248655#step:4:10),"DurationError":25,"NumberOfSqlStmtsWarning":5,"NumberOfSqlStmtsError":10},"shell":"pwsh","useCompilerFolder":true,"powerPlatformSolutionFolder":"","skipUpgrade":true,"projects":[],"projectName":"Garant EDI","installTestFramework":false,"appDependencies":[],"installTestApps":[],"appSourceCopMandatoryAffixes":[],"generateDependencyArtifact":true,"codeSignCertificateUrlSecretName":"codeSignCertificateUrl","githubRunner":"ubuntu-latest","country":"at","runs-on":"ubuntu-latest","additionalCountries":[],"cacheKeepDays":3,"enablePerTenantExtensionCop":false,"customCodeCops":["https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/latest/download/BusinessCentral.LinterCop.current.dll"],"keyVaultCertificateUrlSecretName":"","doNotPublishApps":true,"sendExtendedTelemetryToMicrosoft":false,"adminCenterApiCredentialsSecretName":"adminCenterApiCredentials","type":"PTE","environments":[],"rulesetFile":"CegekaAT.ruleset.json","enableCodeAnalyzersOnTestApps":false,"codeSignCertificatePasswordSecretName":"codeSignCertificatePassword","microsoftTelemetryConnectionString":"InstrumentationKey=cd2cc63e-0f37-4968-b99a-5324[11](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/10596074488/job/29363248655#step:4:11)a314b8;IngestionEndpoint=https://northeurope-2.in.applicationinsights.azure.com/","enableTaskScheduler":false,"doNotRunBcptTests":false,"appDependencyProbingPaths":[{"authTokenSecret":"GHTOKENWORKFLOW","projects":"*","release_status":"release","repo":"https://github.com/CBS-BC-AT/GAR.Base","version":"24.8.0"}],"memoryLimit":"","failOn":"error","deliverToAppSource":{"mainAppFolder":"","productId":"","includeDependencies":[],"continuousDelivery":false},"assignPremiumPlan":false,"templateSha":"578f30d0065aa17fd6bb85[13](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/10596074488/job/29363248655#step:4:13)c7eef725e5474c08","appRevision":0,"partnerTelemetryConnectionString":"","templateBranch":"","obsoleteTagMinAllowedMajorMinor":"","useProjectDependencies":false,"installApps":[],"updateDependencies":false,"installOnlyReferencedApps":true,"installPerformanceToolkit":false,"fullBuildPatterns":[],"treatTestFailuresAsWarnings":false,"applicationDependency":"[18](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/10596074488/job/29363248655#step:4:18).0.0.0","doNotRunTests":false,"applicationInsightsConnectionStringSecretName":"applicationInsightsConnectionString","companyName":"","appBuild":6,"keyVaultCodesignCertificateName":"","templateUrl":"https://github.com/cegekaJG/AL-Go-PTE@cegeka","pullRequestTrigger":"pull_request_target","enableCodeCop":true,"keyVaultCertificatePasswordSecretName":"","keyVaultClientIdSecretName":"","doNotSignApps":false,"UpdateGitHubGoSystemFilesSchedule":"0 2 * * 1,3,5","vsixFile":"latest"}
    _getSecrets: licenseFileUrl,codeSignCertificateUrl,*codeSignCertificatePassword,keyVaultCertificateUrl,*keyVaultCertificatePassword,keyVaultClientId,gitHubPackagesContext,applicationInsightsConnectionString,appDependencyProbingPathsSecrets,AZURE_CREDENTIALS
    _useGhTokenWorkflowForPush: false
Trying to get the secret (licenseFileUrl) from the github environment.
Masking value for licenseFileUrl
Secret (licenseFileUrl) was retrieved from the github environment.
licenseFileUrl successfully read from secret licenseFileUrl
Trying to get the secret (codeSignCertificateUrl) from the github environment.
Could not find secret codeSignCertificateUrl in Github secrets or Azure Key Vault.
Trying to get the secret (codeSignCertificatePassword) from the github environment.
Could not find secret codeSignCertificatePassword in Github secrets or Azure Key Vault.
Trying to get the secret (gitHubPackagesContext) from the github environment.
Could not find secret gitHubPackagesContext in Github secrets or Azure Key Vault.
Trying to get the secret (applicationInsightsConnectionString) from the github environment.
Could not find secret applicationInsightsConnectionString in Github secrets or Azure Key Vault.
Trying to get the secret (AZURE_CREDENTIALS) from the github environment.
Could not find secret AZURE_CREDENTIALS in Github secrets or Azure Key Vault.
Trying to get the secret (GHTOKENWORKFLOW) from the github environment.
Masking value for GHTOKENWORKFLOW
Secret (GHTOKENWORKFLOW) was retrieved from the github environment.
GHTOKENWORKFLOW successfully read from secret GHTOKENWORKFLOW
The following secrets was not found: codeSignCertificateUrl, codeSignCertificatePassword (Secret codeSignCertificatePassword), gitHubPackagesContext, applicationInsightsConnectionString, AZURE_CREDENTIALS
Applying settings from /home/runner/work/GAR.EDI/GAR.EDI/.github/AL-Go-Settings.json
Applying settings from /home/runner/work/GAR.EDI/GAR.EDI/.AL-Go/settings.json
No settings found in /home/runner/work/GAR.EDI/GAR.EDI/.github/CICD.settings.json
No settings found in /home/runner/work/GAR.EDI/GAR.EDI/.AL-Go/CICD.settings.json
No settings found in /home/runner/work/GAR.EDI/GAR.EDI/.AL-Go/cegekaJG.settings.json
Enabling Microsoft telemetry...
```

### Steps to reproduce

The system files come from my AL Go fork (CegekaJG/AL-Go@cegeka)[https://github.com/cegekaJG/AL-Go/tree/cegeka], but the behavior of the workflow is unmodified at this point. The secret `GHTOKENWORKFLOW` is defined as an organization token, and here are the AL Go setting files of one of the failing repos:

`.AL-Go/settings.json`
```json
{
  "$schema": "https://raw.githubusercontent.com/microsoft/AL-Go/v5.1/Schema/algosettingssyntax.json",
  "country": "at",
  "projectName": "Gar EDI",
  "generateDependencyArtifact": true,
  "appDependencyProbingPaths":[
    {
      "repo": "https://github.com/CBS-BC-AT/GAR.Base",
      "version": "24.8.0",
      "release_status": "release",
      "authTokenSecret": "GHTOKENWORKFLOW",
      "projects": "*"
    }
  ]
}
```

`.github/AL-GO-Settings.json`
```json
{
  "$schema": "https://raw.githubusercontent.com/microsoft/AL-Go/v5.1/Schema/algoreposettingssyntax.json",
  "buildModes": [
    "Default"
  ],
  "customCodeCops": [
   "https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/latest/download/BusinessCentral.LinterCop.current.dll"
  ],
  "doNotPublishApps": true,
  "enableCodeCop": true,
  "enablePerTenantExtensionCop": false,
  "enableUICop": true,
  "githubRunner": "ubuntu-latest",
  "rulesetFile": "CegekaAT.ruleset.json",
  "runs-on": "ubuntu-latest",
  "skipUpgrade": true,
  "templateUrl": "https://github.com/cegekaJG/AL-Go-PTE@cegeka",
  "templateFiles": [
    ".github/DeployTo*.ps1",
    ".schemas/*"
  ],
  "type": "PTE",
  "UpdateGitHubGoSystemFilesSchedule": "0 2 * * 1,3,5",
  "useCompilerFolder": true,
  "vsixFile": "latest",
  "templateSha": "578f30d0065aa17fd6bb8513c7eef725e5474c08"
}
```

### Additional context (logs, screenshots, etc.)

Upon closer examination, it looks like since the update, the workflow has stopped reading the `GHTOKENWORKLOW` secret, as indicated by the log of the "Read Secrets" step:

```
Run cegekaJG/AL-Go-Actions/ReadSecrets@cegeka
  with:
    shell: pwsh
    gitHubSecrets: {
    "FLFLICENSEFILEURL": "***",
    "LICENSEFILEURL": "***",
    "github_token": "***",
    "GHTOKENWORKFLOW": "***"
  }
    getSecrets: licenseFileUrl,keyVaultCertificateUrl,*keyVaultCertificatePassword,keyVaultClientId,gitHubPackagesContext,applicationInsightsConnectionString,appDependencyProbingPathsSecrets,AZURE_CREDENTIALS
    useGhTokenWorkflowForPush: false
  env:
    ALGoOrgSettings: 
    ALGoRepoSettings: 
    artifact: https://bcartifacts-exdbf9fwegejdqak.b0[2](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/11357757228/job/31591156643#step:4:2).azurefd.net/sandbox/24.[3](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/11357757228/job/31591156643#step:4:3).21374.21570/at
    keyVaultCodesignCertificateName: 
    generateDependencyArtifact: True
    doNotRunTests: False
    doNotSignApps: True
    useCompilerFolder: True
    Settings: {"repoVersion":"1.0","appDependencies":[],"doNotBuildTests":false,"$schema":"https://raw.githubusercontent.com/microsoft/AL-Go/v5.1/Schema/algosettingssyntax.json","rulesetFile":"CegekaAT.ruleset.json","projectName":"Garant EDI","alwaysBuildAllProjects":false,"testDependencies":[],"appBuild":21[4](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/11357757228/job/31591156643#step:4:4)7483647,"unusedALGoSystemFiles":[],"obsoleteTagMinAllowedMajorMinor":"","githubRunner":"ubuntu-latest","UpdateGitHubGoSystemFilesSchedule":"0 2 * * 1,3,[5](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/11357757228/job/31591156643#step:4:5)","bcptTestFolders":[],"assignPremiumPlan":false,"licenseFileUrlSecretName":"licenseFileUrl","powerPlatformSolutionFolder":"","fullBuildPatterns":[],"enablePerTenantExtensionCop":false,"keyVaultName":"","microsoftTelemetryConnectionString":"InstrumentationKey=cd2cc[6](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/11357757228/job/31591156643#step:4:6)3e-0f37-4968-b99a-532411a314b8;IngestionEndpoint=https://northeurope-2.in.applicationinsights.azure.com/","templateBranch":"","buildModes":["Default"],"appDependencyProbingPaths":[{"authTokenSecret":"GHTOKENWORKFLOW","projects":"*","release_status":"release","repo":"https://github.com/CBS-BC-AT/GAR.Base","version":"24.8.0"}],"keyVaultCodesignCertificateName":"","templateUrl":"https://github.com/cegekaJG/AL-Go-PTE@cegeka","enableCodeCop":true,"appFolders":[],"excludeEnvironments":[],"doNotPublishApps":true,"failOn":"error","codeSignCertificatePasswordSecretName":"codeSignCertificatePassword","artifact":"https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/24.3.213[7](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/11357757228/job/31591156643#step:4:7)4.21570/at","installOnlyReferencedApps":true,"vsixFile":"latest","bcptThresholds":{"DurationWarning":10,"DurationError":25,"NumberOfSqlStmtsWarning":5,"NumberOfSqlStmtsError":10},"appSourceCopMandatoryAffixes":[],"doNotSignApps":true,"installTestApps":[],"keyVaultCertificateUrlSecretName":"","doNotRunBcptTests":false,"deliverToAppSource":{"mainAppFolder":"","productId":"","includeDependencies":[],"continuousDelivery":false},"installApps":[],"installPerformanceToolkit":false,"testFolders":[],"appRevision":0,"companyName":"","enableUICop":true,"enableCodeAnalyzersOnTestApps":false,"cacheKeepDays":3,"runs-on":"ubuntu-latest","enableTaskScheduler":false,"enableExternalRulesets":false,"type":"PTE","generateDependencyArtifact":true,"templateFiles":[".github/DeployTo*.ps1",".schemas/*"],"useProjectDependencies":false,"templateSha":"4116c54c9a70efdd1[8](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/11357757228/job/31591156643#step:4:8)2028e4527f45293202624e","alDoc":{"continuousDeployment":false,"deployToGitHubPages":true,"maxReleases":3,"groupByProject":true,"includeProjects":[],"excludeProjects":[],"header":"Documentation for {REPOSITORY} {VERSION}","footer":"Documentation for <a href=\"https://github.com/{REPOSITORY}\">{REPOSITORY}</a> made with <a href=\"https://aka.ms/AL-Go\">AL-Go for GitHub</a>, <a href=\"https://go.microsoft.com/fwlink/?linkid=2247728\">ALDoc</a> and <a href=\"https://dotnet.github.io/docfx\">DocFx</a>","defaultIndexMD":"## Reference documentation\\n\\nThis is the generated reference documentation for [{REPOSITORY}](https://github.com/{REPOSITORY}).\\n\\nYou can use the navigation bar at the top and the table of contents to the left to navigate your documentation.\\n\\nYou can change this content by creating/editing the **{INDEXTEMPLATERELATIVEPATH}** file in your repository or use the alDoc:defaultIndexMD setting in your repository settings file (.github/AL-Go-Settings.json)\\n\\n{RELEASENOTES}","defaultReleaseMD":"## Release reference documentation\\n\\nThis is the generated reference documentation for [{REPOSITORY}](https://github.com/{REPOSITORY}).\\n\\nYou can use the navigation bar at the top and the table of contents to the left to navigate your documentation.\\n\\nYou can change this content by creating/editing the **{INDEXTEMPLATERELATIVEPATH}** file in your repository or use the alDoc:defaultReleaseMD setting in your repository settings file (.github/AL-Go-Settings.json)\\n\\n{RELEASENOTES}"},"adminCenterApiCredentialsSecretName":"adminCenterApiCredentials","githubRunnerShell":"pwsh","skipUpgrade":true,"memoryLimit":"","country":"at","environments":[],"runNumberOffset":0,"sendExtendedTelemetryToMicrosoft":false,"codeSignCertificateUrlSecretName":"codeSignCertificateUrl","installTestFramework":false,"keyVaultCertificatePasswordSecretName":"","repoName":"GAR.EDI","installTestRunner":false,"useCompilerFolder":true,"treatTestFailuresAsWarnings":false,"cacheImageName":"my","doNotRunTests":false,"applicationInsightsConnectionStringSecretName":"applicationInsightsConnectionString","trustMicrosoftNuGetFeeds":true,"keyVaultClientIdSecretName":"","shell":"pwsh","partnerTelemetryConnectionString":"","configPackages":[],"pullRequestTrigger":"pull_request_target","versioningStrategy":15,"additionalCountries":[],"installTestLibraries":false,"ghTokenWorkflowSecretName":"ghTokenWorkflow","customCodeCops":["https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/latest/download/BusinessCentral.LinterCop.current.dll"],"updateDependencies":false,"projects":[],"applicationDependency":"18.0.0.0"}
Run /home/runner/work/_actions/cegekaJG/AL-Go-Actions/cegeka/ReadSecrets/../Invoke-AlGoAction.ps1 -ActionName "ReadSecrets" -Action {
  /home/runner/work/_actions/cegekaJG/AL-Go-Actions/cegeka/ReadSecrets/../Invoke-AlGoAction.ps1 -ActionName "ReadSecrets" -Action {
    /home/runner/work/_actions/cegekaJG/AL-Go-Actions/cegeka/ReadSecrets/ReadSecrets.ps1 -gitHubSecrets '{
    "FLFLICENSEFILEURL": "***",
    "LICENSEFILEURL": "***",
    "github_token": "***",
    "GHTOKENWORKFLOW": "***"
  }' -getSecrets $ENV:_getSecrets -useGhTokenWorkflowForPush $ENV:_useGhTokenWorkflowForPush
  }
  shell: /usr/bin/pwsh -command ". '{0}'"
  env:
    ALGoOrgSettings: 
    ALGoRepoSettings: 
    artifact: https://bcartifacts-exdbf[9](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/11357757228/job/31591156643#step:4:9)fwegejdqak.b02.azurefd.net/sandbox/24.3.21374.21570/at
    keyVaultCodesignCertificateName: 
    generateDependencyArtifact: True
    doNotRunTests: False
    doNotSignApps: True
    useCompilerFolder: True
    Settings: {"repoVersion":"1.0","appDependencies":[],"doNotBuildTests":false,"$schema":"https://raw.githubusercontent.com/microsoft/AL-Go/v5.1/Schema/algosettingssyntax.json","rulesetFile":"CegekaAT.ruleset.json","projectName":"Garant EDI","alwaysBuildAllProjects":false,"testDependencies":[],"appBuild":2147483647,"unusedALGoSystemFiles":[],"obsoleteTagMinAllowedMajorMinor":"","githubRunner":"ubuntu-latest","UpdateGitHubGoSystemFilesSchedule":"0 2 * * 1,3,5","bcptTestFolders":[],"assignPremiumPlan":false,"licenseFileUrlSecretName":"licenseFileUrl","powerPlatformSolutionFolder":"","fullBuildPatterns":[],"enablePerTenantExtensionCop":false,"keyVaultName":"","microsoftTelemetryConnectionString":"InstrumentationKey=cd2cc63e-0f37-4968-b99a-532411a314b8;IngestionEndpoint=https://northeurope-2.in.applicationinsights.azure.com/","templateBranch":"","buildModes":["Default"],"appDependencyProbingPaths":[{"authTokenSecret":"GHTOKENWORKFLOW","projects":"*","release_status":"release","repo":"https://github.com/CBS-BC-AT/GAR.Base","version":"24.8.0"}],"keyVaultCodesignCertificateName":"","templateUrl":"https://github.com/cegekaJG/AL-Go-PTE@cegeka","enableCodeCop":true,"appFolders":[],"excludeEnvironments":[],"doNotPublishApps":true,"failOn":"error","codeSignCertificatePasswordSecretName":"codeSignCertificatePassword","artifact":"https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/24.3.21374.21570/at","installOnlyReferencedApps":true,"vsixFile":"latest","bcptThresholds":{"DurationWarning":[10](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/11357757228/job/31591156643#step:4:10),"DurationError":25,"NumberOfSqlStmtsWarning":5,"NumberOfSqlStmtsError":10},"appSourceCopMandatoryAffixes":[],"doNotSignApps":true,"installTestApps":[],"keyVaultCertificateUrlSecretName":"","doNotRunBcptTests":false,"deliverToAppSource":{"mainAppFolder":"","productId":"","includeDependencies":[],"continuousDelivery":false},"installApps":[],"installPerformanceToolkit":false,"testFolders":[],"appRevision":0,"companyName":"","enableUICop":true,"enableCodeAnalyzersOnTestApps":false,"cacheKeepDays":3,"runs-on":"ubuntu-latest","enableTaskScheduler":false,"enableExternalRulesets":false,"type":"PTE","generateDependencyArtifact":true,"templateFiles":[".github/DeployTo*.ps1",".schemas/*"],"useProjectDependencies":false,"templateSha":"4[11](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/11357757228/job/31591156643#step:4:11)6c54c9a70efdd182028e4527f45293202624e","alDoc":{"continuousDeployment":false,"deployToGitHubPages":true,"maxReleases":3,"groupByProject":true,"includeProjects":[],"excludeProjects":[],"header":"Documentation for {REPOSITORY} {VERSION}","footer":"Documentation for <a href=\"https://github.com/{REPOSITORY}\">{REPOSITORY}</a> made with <a href=\"https://aka.ms/AL-Go\">AL-Go for GitHub</a>, <a href=\"https://go.microsoft.com/fwlink/?linkid=2247728\">ALDoc</a> and <a href=\"https://dotnet.github.io/docfx\">DocFx</a>","defaultIndexMD":"## Reference documentation\\n\\nThis is the generated reference documentation for [{REPOSITORY}](https://github.com/{REPOSITORY}).\\n\\nYou can use the navigation bar at the top and the table of contents to the left to navigate your documentation.\\n\\nYou can change this content by creating/editing the **{INDEXTEMPLATERELATIVEPATH}** file in your repository or use the alDoc:defaultIndexMD setting in your repository settings file (.github/AL-Go-Settings.json)\\n\\n{RELEASENOTES}","defaultReleaseMD":"## Release reference documentation\\n\\nThis is the generated reference documentation for [{REPOSITORY}](https://github.com/{REPOSITORY}).\\n\\nYou can use the navigation bar at the top and the table of contents to the left to navigate your documentation.\\n\\nYou can change this content by creating/editing the **{INDEXTEMPLATERELATIVEPATH}** file in your repository or use the alDoc:defaultReleaseMD setting in your repository settings file (.github/AL-Go-Settings.json)\\n\\n{RELEASENOTES}"},"adminCenterApiCredentialsSecretName":"adminCenterApiCredentials","githubRunnerShell":"pwsh","skipUpgrade":true,"memoryLimit":"","country":"at","environments":[],"runNumberOffset":0,"sendExtendedTelemetryToMicrosoft":false,"codeSignCertificateUrlSecretName":"codeSignCertificateUrl","installTestFramework":false,"keyVaultCertificatePasswordSecretName":"","repoName":"GAR.EDI","installTestRunner":false,"useCompilerFolder":true,"treatTestFailuresAsWarnings":false,"cacheImageName":"my","doNotRunTests":false,"applicationInsightsConnectionStringSecretName":"applicationInsightsConnectionString","trustMicrosoftNuGetFeeds":true,"keyVaultClientIdSecretName":"","shell":"pwsh","partnerTelemetryConnectionString":"","configPackages":[],"pullRequestTrigger":"pull_request_target","versioningStrategy":[15](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/11357757228/job/31591156643#step:4:15),"additionalCountries":[],"installTestLibraries":false,"ghTokenWorkflowSecretName":"ghTokenWorkflow","customCodeCops":["https://github.com/StefanMaron/BusinessCentral.LinterCop/releases/latest/download/BusinessCentral.LinterCop.current.dll"],"updateDependencies":false,"projects":[],"applicationDependency":"[18](https://github.com/CBS-BC-AT/GAR.EDI/actions/runs/11357757228/job/31591156643#step:4:18).0.0.0"}
    _getSecrets: licenseFileUrl,keyVaultCertificateUrl,*keyVaultCertificatePassword,keyVaultClientId,gitHubPackagesContext,applicationInsightsConnectionString,appDependencyProbingPathsSecrets,AZURE_CREDENTIALS
    _useGhTokenWorkflowForPush: false
Trying to get the secret (licenseFileUrl) from the github environment.
Masking value for licenseFileUrl
Secret (licenseFileUrl) was retrieved from the github environment.
licenseFileUrl successfully read from secret licenseFileUrl
Trying to get the secret (gitHubPackagesContext) from the github environment.
Could not find secret gitHubPackagesContext in Github secrets or Azure Key Vault.
Trying to get the secret (applicationInsightsConnectionString) from the github environment.
Could not find secret applicationInsightsConnectionString in Github secrets or Azure Key Vault.
Trying to get the secret (appDependencyProbingPathsSecrets) from the github environment.
Could not find secret appDependencyProbingPathsSecrets in Github secrets or Azure Key Vault.
Trying to get the secret (AZURE_CREDENTIALS) from the github environment.
Could not find secret AZURE_CREDENTIALS in Github secrets or Azure Key Vault.
The following secrets was not found: gitHubPackagesContext, applicationInsightsConnectionString, appDependencyProbingPathsSecrets, AZURE_CREDENTIALS
Applying settings from /home/runner/work/GAR.EDI/GAR.EDI/.github/AL-Go-Settings.json
Applying settings from /home/runner/work/GAR.EDI/GAR.EDI/.AL-Go/settings.json
No settings found in /home/runner/work/GAR.EDI/GAR.EDI/.github/Pull Request Build.settings.json
No settings found in /home/runner/work/GAR.EDI/GAR.EDI/.AL-Go/Pull Request Build.settings.json
No settings found in /home/runner/work/GAR.EDI/GAR.EDI/.AL-Go/cegekaJG.settings.json
Enabling Microsoft telemetry...
```

Since the last stable version, based on a2a51be438318a7e355fa9044815cf7890ffed1a, there has been a rework of the `Actions/ReadSecrets/ReadSecrets.ps1` script, so I assume this change introduced the error. Here's a comparison between the last known working version, and the most recent commit:
[Actions/ReadSecrets/ReadSecrets.ps1](https://github.com/microsoft/AL-Go/compare/a2a51be438318a7e355fa9044815cf7890ffed1a..5bb4f65ffe64f5328a70a288d04640786aa467ec#diff-6b9104547992784582cd45b1ea5bc99c3d7529f609a9862c7dbca21dc7eca190)

**Comment by freddydk** [comment]
The rework of ReadSecrets was done quite some time ago and was done because ReadSecrets in the old days would read all secrets available to the workflow (also the ones not needed) - that has caused issues.

It looks like your merge has gone wrong.

In the latest version of AL-Go, ReadSecrets will loop through AppDependencyProbingPaths to determine which secrets to read:
![Image](https://github.com/user-attachments/assets/688f4a2e-c304-4cbd-b4c3-9a72d31e8a18)

Instead your fork will try to read the secret called `appDependencyProbingPathsSecrets` (which in v5 was the flag to tell ReadSecrets to read probing paths secrets - in v6 it is called `AppDependencySecrets`

**Comment by cegekaJG** [comment]
I'm not sure I understand - I'm looking at my custom branch and `appDependencyProbingPathsSecrets` isn't used once in the entire repo, so I'm not sure where it would be getting that key name from. Also, there are no differences between my fork and the official repo for the `ReadSecret`-scripts. The only scripts I've altered are for `CheckForUpdates` and `Deploy`, the latter of which only has a change to the log output. The only workflow that has been modified is `PullRequestHandler`, but only the step triggers have been changed here.
Beyond that, there are no differences between the two repos in terms of scripts, so I don't see which change in my repo causes the "Read secrets" step in the workflow to malfunction.

**Comment by freddydk** [comment]
Please create a public repository, using public AL-Go, which showcases the problem. Then I will have a look.

**Comment by cegekaJG** [comment]
I've created a public repo using both the official and custom AL-Go, and neither are loading GHTOKENWORKFLOW despite the fact it's listed in the settings.
Here's the CI/CD build from 6.0: https://github.com/cegekaJG/TokenTest/actions/runs/11404925946/job/31735220569
And here's the build using my custom template: https://github.com/cegekaJG/TokenTest/actions/runs/11405889532/job/31738428964

**Comment by freddydk** [comment]
In that repo, repo settings file is:
```
{
  "type": "PTE",
  "templateUrl": "https://github.com/microsoft/AL-Go-PTE@v6.0",
  "templateSha": "a4fa71b5aa7569f9bf70be3f41db7e738abda80e"
}
```
and project settings file is:
```
{
  "country": "us",
  "appFolders": [],
  "testFolders": [],
  "bcptTestFolders": []
}
```

Why do you think it should read the GhTokenWorkflow secret?
There's nothing here that needs it.

**Comment by cegekaJG** [comment]
I thought it would try to read it since it attempts to read a bunch of other secrets that are neither defined nor used in this repo directly.
In any case, I added a dependency and both the official version and my custom fork are both reading the secret properly, so it must have something to do with the repo - though the workflows are the same as my fork. Looking at some other repos, it seems that only this one repo appears to have this problem.

**Comment by freddydk** [comment]
The other secrets that it is reading are secrets, which (if they exist) would cause AL-Go to use them.

**Comment by freddydk** [comment]
I still think your _BuildALGoProject.yaml is wrong (or CICD.yaml).
If your merge was correct, an update al-go system files should fix this problem.

**Comment by cegekaJG** [comment]
As you can see [here](https://github.com/cegekaJG/AL-Go-Actions/compare/main..testbranch6) and [here](https://github.com/cegekaJG/AL-Go-PTE/compare/main..testbranch6), there is no effective difference between the workflows, but I've been running "Update AL-Go" multiple times and it still doesn't work.
I unfortunately can't show the afflicted repo itself since it's private and company property, but the system files are up to date with the branch `testbranch6`.

**Comment by cegekaJG** [comment]
I've just run an update and enabled the option to directly push to the branch. While the build during the PR check always failed, the CI/CD workflow triggered by the new push actually read `GHTOKENWORKFLOW` correctly. I can't say why that is, but it seems to work now.

**Comment by freddydk** [comment]
In the old (non-functioning) version of _BuildALGoProject.yaml - I am 99,999% sure that you would find that this part:

![Image](https://github.com/user-attachments/assets/4f1e8cbb-ca5e-4ced-9b78-f6ec87b05766)

have `appDependencySecrets` replaced by `appDependencyProbingPathSecrets`

It was like that in the old days (and it shows in your logs in your very first post):
![Image](https://github.com/user-attachments/assets/d0a223d4-0009-46fc-8b62-eb6b87351b92)

**Comment by cegekaJG** [comment]
You're correct, I'm just a bit confused where this came from. In any case, thanks for the help.
