### ISSUE TITLE
[Bug]: Update System Files fails with customized template due to missing settings.schema.json

### ISSUE THREAD

**Issue by ps610** [microsoft/AL-Go#1732]
### AL-Go version

freddydk/customize

### Describe the issue

We have a customized version of the AL-Go-PTE template to use it together with COSMO Alpaca:
https://github.com/cosmoconsult/Alpaca-PTE
We heavily rely on the features introduced in here: https://github.com/microsoft/AL-Go/pull/853

Since [this recent change in Freddy's customize branch](https://github.com/freddydk/AL-Go/commit/0f133fe3237ad370f4066539370e9abc62381884), we receive reports that both the Update System Files workflow and the Update Check (during a CI/CD run for example) are failing. The change introduces the settings schema contributed by: https://github.com/microsoft/AL-Go/pull/1227

In our custom job to update the Alpaca system files, we use the same logic as AL-Go to read the settings (the workflow token):
https://github.com/cosmoconsult/Alpaca-PTE/blob/2d18c6e0f87bacfa0b0dc962c0ec244f282307fe/.github/workflows/UpdateGitHubGoSystemFiles.yaml#L190-L196 

Trying to update our template from freddys branch, like we usually do, does not work now:
https://github.com/cosmoconsult/Alpaca-PTE/actions/runs/15019244161/job/42204296107#step:8:112
> Cannot find path '/home/runner/work/Alpaca-PTE/Alpaca-PTE/settings.schema.json' because it does not exist.

Running the CI/CD workflow (with the Update Check) fails with this error:
https://github.com/cosmoconsult/Alpaca-PTE/actions/runs/15021315474/job/42210994374#step:5:340
> Unexpected error when running action. Error Message: The property '$schema' cannot be found on this object. Verify that the property exists., StackTrace: at GetModifiedSettingsContent, /home/runner/work/_actions/freddydk/AL-Go/customize/Actions/CheckForUpdates/CheckForUpdates.HelperFunctions.ps1: line 505 <- at <ScriptBlock>, /home/runner/work/_actions/freddydk/AL-Go/customize/Actions/CheckForUpdates/CheckForUpdates.ps1: line 259 <- at <ScriptBlock>, /home/runner/work/_actions/freddydk/AL-Go/customize/Actions/CheckForUpdates/CheckForUpdates.ps1: line 218 <- at <ScriptBlock>, /home/runner/work/_temp/da356237-10a4-4b04-ad61-a47c409175f4.ps1: line 3 <- at <ScriptBlock>, /home/runner/work/_actions/freddydk/AL-Go/customize/Actions/Invoke-AlGoAction.ps1: line 17 <- at <ScriptBlock>, /home/runner/work/_temp/da356237-10a4-4b04-ad61-a47c409175f4.ps1: line 2 <- at <ScriptBlock>, <No file>: line 1

### Expected behavior

Is the schema file/setting required in every (existing) repository? How does the update workflow work with this, and should this be handled differently in a customized template?

### Steps to reproduce

Create a repository from our Alpaca-PTE template and run Update AL-Go system files or CI/CD.

### Additional context (logs, screenshots, etc.)

The [AL-Go main branch](https://github.com/microsoft/AL-Go/blob/9ea437f59fe54d77f6946a42f93cc1e7867f90db/Templates/Per%20Tenant%20Extension/.AL-Go/settings.json#L2C3-L2C4) (and [freddys too](https://github.com/freddydk/AL-Go/blob/c97fd3377e8b4fd796813947a8daeab376f3a539/Templates/Per%20Tenant%20Extension/.AL-Go/settings.json#L2)) links this schema file: https://raw.githubusercontent.com/microsoft/AL-Go-Actions/main/settings.schema.json
But that file does not exist, yet?

**Comment by ps610** [comment]
@mazhelez I already messaged with freddy directly about this, but he asked me to write an issue so you can maybe take a look.

**Comment by freddydk** [comment]
This file: https://raw.githubusercontent.com/microsoft/AL-Go-Actions/main/settings.schema.json will exist - and like all other references it will be modified to point to your template repo.
I think the problem here was caused by an error when I merged main into my PR yesterday.
Please try again now - just pushed a new change

**Comment by ps610** [comment]
Sorry, no change. Both the update check and the update itself still fail with the same errors:
https://github.com/cosmoconsult/Alpaca-PTE/actions/runs/15037164534/job/42260998836#step:5:340
https://github.com/cosmoconsult/Alpaca-PTE/actions/runs/15037136270/job/42260910777#step:8:112

**Comment by freddydk** [comment]
try again

**Comment by ps610** [comment]
The update check works again now.

But the update itself still fails at `ReadSettings` (more precisely at `ValidateSettings`):
https://github.com/cosmoconsult/Alpaca-PTE/actions/runs/15037776615/job/42262638854#step:8:112
> Join-Path: /home/runner/work/Alpaca-PTE/Alpaca-PTE/AL-Go-Helper.ps1:880
Line |
 880 |  … sSchemaFile = Join-Path $PSScriptRoot "settings.schema.json" -Resolve
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path
     | '/home/runner/work/Alpaca-PTE/Alpaca-PTE/settings.schema.json' because
     | it does not exist.
Error: Process completed with exit code 1.

**Comment by ps610** [comment]
I just tried to set the schema setting in `.AL-Go/settings.json` in our template to https://raw.githubusercontent.com/freddydk/AL-Go/customize/Actions/settings.schema.json, but that doesn't help either.
https://github.com/cosmoconsult/Alpaca-PTE/commit/efee5a85e61b156e06114ed8413d93f3ba277b9a

**Comment by freddydk** [comment]
It looks like you have a copy of AL-Go-Helper.ps1 somewhere, which you are running?
Maybe you download that - then you also need to download settings.schema.json to the same folder

**Comment by freddydk** [comment]
Here:

![Image](https://github.com/user-attachments/assets/38098d40-5dd4-4f42-ba77-4ea3ec78be70)

Add a download of settings.schema.json as well as the others.

**Comment by ps610** [comment]
Ah, indeed, thanks for pointing out! Work again now 👍
